name: Check source code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH=$PATH:$HOME/.local/bin/
        poetry install
    - name: Lint with flake8
      run: |
        # stop the build if source code does not folows PEP8
        poetry run flake8 . --count --show-source --statistics
    - name: Check types with mypy
      run: |
        poetry run mypy .
    - name: Test with pytest
      run: |
        poetry run pytest -v
